### ISSUE TITLE
YAML packaging

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#101]
Looking at the big install.yaml file and all the configurations possible, I think it would help people to provide a way of packaging YAML files.

Possible variables:
- namespace
- service account names
- MIN_PORT
- MAX_PORT
- images version (for later)
- RBAC on/off ???

The default variable should reflect the current install.yaml.

We should also update the documentation to add installation step using helm on top of what we already have.

I don't think it's urgent for 0.1 but interesting to have.

/cc @rodcloutier

**Comment by Kuqd** [comment]
https://github.com/SUSE/helm-certgen

**Comment by markmandel** [comment]
Chat from today.
TL;DR - We will go with Helm.

```
Mark Mandel [1:12 PM]
@Cyril Tovena chatting about Helm - quick thought - if we wanted to do a quick spike, to see what a helm chart for Agones looked like - easy/hard ?


Rod Cloutier [1:12 PM]
Would be fairly easy for us to do.

Mark Mandel [1:12 PM]
Sounds like that may be a nice way forward? Just to try it out, see how it feels?
especially if it will handle the certs issues
and installing helm doesn't look particularly onerous

Rod Cloutier [1:13 PM]
We don`t need to use Helm on both the client and server side. You can generate a yaml from Helm charts and do a `kubectl apply` afterward.

Mark Mandel [1:13 PM]
OH REALLY?
this is why I ask you smart people the questions :smile:
I did not know this
Sounds like Helm is a winner winner chicken dinner?

Cyril Tovena [1:15 PM]
like I said you could try to even get a stable chart
which is good for visibility
I suggest that I give a go with helm without certs and move from there

Mark Mandel [1:17 PM]
SGTM
I'll copy paste this little chat into the ticket, just for posterity/transparency
```

**Comment by Kuqd** [comment]
while reading the doc I found that you can run post installation test : https://docs.helm.sh/developing_charts/#chart-tests

That's just awesome, I'm thinking to use flag switch in the controller container to run a simple gs/pod creation and release control.

WDYT ? I'm planing to introduce this after a first version so probably create a new issue if we all think that's a boomer.

**Comment by markmandel** [comment]
We do have a need for #37 (End to end tests) - so maybe this helps with both tickets!

**Comment by rodcloutier** [comment]
Just be careful with this as you now need to install tiller in the cluster to make your tests. This is nice to use a sanity check for the user but I would probably not use this as end to end tests.

**Comment by markmandel** [comment]
But wouldn't we need to install tiller anyway, so we could install Agones, so we could do end to end tests? :smiley:

**Comment by markmandel** [comment]
The other thought I had, if there is a way, is that there is a light test for end users, and then there's the _full_ test for the actual e2e tests - if that is possible.

**Comment by Kuqd** [comment]
we can do a full test for the user using this ! (create a gs, wait for it to have a pod assigned, communicate)

I'm having hard time with end to end tests are really for us ? is it in an actual cluster ?

**Comment by markmandel** [comment]
> I'm having hard time with end to end tests are really for us ? is it in an actual cluster ?
Apologies, I'm not following?

So one thing I'm very much thinking - we do want automated testing of the Helm chart as well as e2e tests.

So this is likely more a conversation for #37 - but part of that would be to install via helm, and then make sure things work. But we could defer the testing work until we have a valid Helm install.

This actually makes me even more happy about using Helm for this work - it has lots of useful tools!

**Comment by Kuqd** [comment]
Sorry midnight comment, but yes I was asking about the scope of e2e tests.

**Comment by fooock** [comment]
To see the full scope of this feature take a look to [this comment](https://github.com/GoogleCloudPlatform/agones/pull/149#issuecomment-377553654)

## Work breakdown

- [ ] Create a Helm chart that can be installed and used on a cluster + docs (see #149)
- [ ] Migrate `build/` tooling to use Helm
- [ ] Write Helm test (*details to be discussed*)
- [ ] Chart repository 
- [ ] Update release process

**Comment by markmandel** [comment]
@fooock we'll want to add a work item of adding the ability to list namespaces that the gameservers will run in, and create service accounts for them - see #146 and #154 for context.

**Comment by Kuqd** [comment]
Every remaining work has it's own issue, let's close it.
